base/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^home/$', views.home, name="home"),
    url(r'^registration/$', views.registration, name="registration_view"),
    url(r'^confirm-email/(?P<key>.*)/$', views.confirm_email, name="confirm_email"),
    url(r'^login/$', views.login, name="login_view"),
    url(r'^logout/$', views.logout, name="logout_view"),
    url(r'^sentence_text_analysis/$', views.sentence_text_analysis, name="sentence_text_analysis"),
    url(r'^aggregate_related_tweets/$', views.aggregate_related_tweets, name="aggregate_related_tweets"),
    url(r'^download_tweets/$', views.download_tweets, name="download_tweets"),
    url(r'^aggregate_user_tweets/$', views.aggregate_user_tweets, name="aggregate_user_tweets"),
    url(r'^download_User_tweets/$', views.download_User_tweets, name="download_User_tweets"),
    url(r'^tweeter_user_text_analysis/$', views.tweeter_user_text_analysis, name="tweeter_user_text_analysis"),
    url(r'^tweeter_user_text_analysis_display/$', views.tweeter_user_text_analysis_display, name="tweeter_user_text_analysis_display"),
    url(r'^tweeter_word_text_analysis/$', views.tweeter_word_text_analysis, name="tweeter_word_text_analysis"),
    url(r'^tweeter_word_text_analysis_display/$', views.tweeter_word_text_analysis_display,
        name="tweeter_word_text_analysis_display"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns_text_analysis/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
import django
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('base/home')),
    url(r'^admin/', admin.site.urls),
    url(r'^base/', include('base.urls', namespace="base")),
    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_admin = models.IntegerField(default=0)
    is_requester = models.IntegerField(default=0)
    is_worker = models.IntegerField(default=1)
    confirmation_code = models.TextField(blank=True)
class SentenceTextData(models.Model):
    user = models.ForeignKey(User, null=True, default=None, blank=True)
    text_message = models.CharField(max_length=255, blank=True)
    json_name = models.CharField(max_length=255, blank=True)
    created = models.DateTimeField(editable=False, auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    is_published = models.IntegerField(default=0)

base/views.py
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from base.models import *
import uuid
from django.db import IntegrityError
import smtplib
from email.mime.text import MIMEText
from django.contrib.auth import authenticate
from django.core.files.storage import FileSystemStorage
import json
from base.models import *
from django.shortcuts import render_to_response
from django.template import RequestContext
from twitter import *
import datetime
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import tweepy
from tweepy import OAuthHandler

#Tweepy authintication

consumer_key = 'LglekCkggFHeAKwaAZ0webw4d'
consumer_secret = 'LoIRSZ2EiIzFiwvlFQv7FyYPBecFwchCzAnnusfuj8Pq0OAnju'
access_token_key = '923076988549529600-3qU3190l2W7lbrGt4VC6UstEKa5zdu6'
access_token_secret = 'rwNWjG2QdG0r7ny4B2C6t4jt8RmbGS6vRaAVxGUnVlycN'
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token_key, access_token_secret)
# Create your views here.
def home(request):
    return render(request, 'base/home.html')


def registration(request):
    # registration module
    if request.user.is_authenticated():
        return HttpResponseRedirect('/base/home/')

    elif request.method == "POST":
        user_username = request.POST['username']
        user_password = request.POST['password']
        user_email = request.POST['email']
        user_name = request.POST['name']

        # checking existing email.
        existing_email = User.objects.filter(email=user_email).first()
        if existing_email is not None:
            message = '"' + user_email + '" already exist. Please try with a different email.'

            return render(request, 'base/basic/registration.html',
                          {'error_message': message})

        try:
            user = User.objects.create_user(username=user_username, first_name=user_name, email=user_email)
        except IntegrityError as e:

            e.message = '"' + user_username + '" already exist. Please try with a different username.'

            return render(request, 'base/basic/registration.html',
                          {'error_message': e.message})

        user.set_password(raw_password=user_password)

        user.is_staff = True
        user.is_superuser = False
        user.is_active = False
        user.save()

        confirmation_code = str(uuid.uuid4())

        profile = Profile(user_id=user.pk, is_worker=1, confirmation_code=confirmation_code)
        profile.save()

        # START confirmation email
        target_url = "http://157.7.242.91/base/confirm-email/" + confirmation_code

        sender = 'noreply@codenext.com'
        recipient = user_email
        message = '<p>Dear Mr. ' + user_name + ',</p><p>You have successfully registered. Please <a href="' + target_url + '">click here</a> to confirm your registration.</p><p>Thanks,</p><p>Team CodeNext</p>'

        msg = MIMEText(message, 'html')
        msg['Subject'] = "CodeNext: Registration"
        msg['From'] = sender
        msg['To'] = recipient

        server = smtplib.SMTP_SSL(settings.EMAIL_HOST, settings.EMAIL_PORT)
        server.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)
        server.sendmail(sender, [recipient], msg.as_string())
        server.quit()
        # END confirmation email


        return render(request, 'base/basic/registration.html',
                      {'success_message': 'Account activation link has been sent to you email address. Please check.'})
    else:
        return render(request, 'base/basic/registration.html')
def confirm_email(request, key):
    try:
        profile = Profile.objects.get(confirmation_code = key)
        User.objects.filter(id=profile.user_id).update(is_active = 1)

        # update previous confirmation code to prevent activate later if admin block this user
        profile = Profile.objects.filter(confirmation_code = key).update(confirmation_code = '')

        message = "You account has been activate"
        return render(request, 'base/basic/confirm_email.html',{ 'success_message': message })

    except:
        message = "Link expired"
        return render(request, 'base/basic/confirm_email.html',{ 'error_message': message })


def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/base/home/')

    else:

        from django.contrib.auth import login
        loginStatus = request.user.is_authenticated

        user = None
        print(loginStatus)

        if request.method == 'POST':
            # uname = request.POST['username']

            uemail = request.POST['email']
            pword = request.POST['password']
            LoginRequestUser = User.objects.filter(email=uemail).first()
            user = authenticate(username=LoginRequestUser.username, password=pword)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # return HttpResponseRedirect('/base/begin/')
                    return HttpResponseRedirect('/base/home/')
                else:
                    return render(request, 'base/basic/login.html', {'message': "Its not active user"})
            else:
                return render(request, 'base/basic/login.html',
                              {'message': "Invalid login or your account is inactive"})

        elif request.method == 'GET':
            if (loginStatus == True):
                return HttpResponseRedirect('/base/home/')
            else:
                return render(request, 'base/basic/login.html', {})
    return render(request, 'base/basic/login.html', {'message': "Invalid User name Or Password"})

def logout(request):
    if request.user.is_authenticated():
        from django.contrib.auth import logout
        logout(request)
        return HttpResponseRedirect('/base/login')
    else:
        return HttpResponseRedirect('/base/login')




def sentence_text_analysis(request):
        user_id = request.user.id
        if request.method == 'POST':
            # upload json file

            myfile = request.FILES['json']
            fs = FileSystemStorage(settings.MEDIA_ROOT + '/temp/')
            json_filename = fs.save(myfile.name, myfile)

            fo = open(settings.MEDIA_ROOT + '/temp/' + json_filename,"r")
            file_data= fo.read()
            fo.close()

            json_data = json.loads(json.dumps(file_data))

            decoded = json.loads('{"sns_text_analysis": ' + json_data + '}')

            for item in  decoded["sns_text_analysis"]:
                links = item["links"]
                nodes = item["nodes"]

            text_message = ""
            sentenceTextData = SentenceTextData()
            sentenceTextData.user_id = user_id
            sentenceTextData.text_message = request.POST['textMessage']
            text_message = sentenceTextData.text_message
            sentenceTextData.json_name = json_filename

            # sentenceTextData.save()




            # print(json.dumps(nodes))


            return render(request, 'base/sentence_text_analysis/display_sentence_text_analysis_result.html',
                          {'text_message': text_message,'group':json.dumps(nodes),'source':json.dumps(links)})

        else:
            return render(request, 'base/sentence_text_analysis/sentence_text_analysis_form.html')

def aggregate_related_tweets(request):
    if request.method == 'POST':
        search_word = request.POST['search_word']
        results = []

        api = tweepy.API(auth_handler=auth)
        latest=api.search(q=search_word,since_id='1', count=100)


        for fr in latest:
            status = fr.text
            tweet_date = fr.created_at
            lastId=fr.id
            results.append({'status': status, 'tweet_date': tweet_date.strftime('%d-%m-%Y %H:%M:%S')})

        latest_2=api.search(q=search_word, since_id='1',count=100,max_id=lastId)
        for fr in latest_2:
            status = fr.text
            tweet_date = fr.created_at
            lastId = fr.id
            results.append({'status': status, 'tweet_date': tweet_date.strftime('%d-%m-%Y %H:%M:%S')})
        latest_3=api.search(q=search_word,since_id='1', count=100,max_id=lastId)
        for fr in latest_3:
            status = fr.text
            tweet_date = fr.created_at
            lastId = fr.id
            results.append({'status': status, 'tweet_date': tweet_date.strftime('%d-%m-%Y %H:%M:%S')})
        latest_4 = api.search(q=search_word,since_id='1', count=100, max_id=lastId)
        for fr in latest_4:
            status = fr.text
            tweet_date = fr.created_at
            lastId = fr.id
            results.append({'status': status, 'tweet_date': tweet_date.strftime('%d-%m-%Y %H:%M:%S')})
        latest_5 = api.search(q=search_word,since_id='1', count=100, max_id=lastId)
        for fr in latest_5:
            status = fr.text
            tweet_date = fr.created_at
            results.append({'status': status, 'tweet_date': tweet_date.strftime('%d-%m-%Y %H:%M:%S')})
        # print(len(results))
        return render(request, 'base/aggregate_related_tweets/aggregate_tweets.html', {'results': results})
    else:
        return render(request, 'base/aggregate_related_tweets/aggregate_tweets.html', {})



def download_tweets(request):
    try:
        import csv
        new_results = []
        results = request.POST.get('results')
        numberOfFiles = request.POST.get('numberOfFiles')

        decoded = json.loads('{"tweetLists": ' + results + '}')

        file_name = "Tweets.csv"
        dest_url = settings.MEDIA_ROOT + '/' + file_name
        fx = open(dest_url, "w")

        fx.write("status\n")
        count = 0;
        for item in decoded["tweetLists"]:
            if (count < int(numberOfFiles)):

base/templates/base/footer.html
<!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Location</h3>
                        <p>
                            504, West-11, 1-5-1 Chofugaoka,<br/>
                            Chofu, Tokyo, Japan.
                        </p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Facebook</span><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Google Plus</span><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Twitter</span><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Linked In</span><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><span class="sr-only">Dribble</span><i class="fa fa-fw fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About CodeNext</h3>
                        <p>SNS text Analysis: Workplace for AI.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; CodeNext 2017
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

base/templates/base/header.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <ul class="dropdown-nav ">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"><i class="fa fa-2x fa-bars" aria-hidden="true"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'base:sentence_text_analysis' %}">Sentence Text Analysis</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'base:tweeter_user_text_analysis' %}">twitter-user Text Analysis</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'base:tweeter_word_text_analysis' %}">twitter-word Text Analysis</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'base:aggregate_user_tweets' %}">Aggregate user’s tweet</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'base:aggregate_related_tweets' %}">Aggregate tweet related word</a></li>
                    </ul>
                </li>
            </ul>
    </div>




      <ul class="nav navbar-nav navbar-right">

{# {% if user.is_authenticated %}#}
{#        <li><a href="{% url 'base:logout_view' %}">Logout</a></li>#}
{#        <li><small>Signed in as {{ user.first_name }}</small></li>#}
{#{% else %}#}
{#<li><a href="{% url 'base:home' %}">Home</a> </li>#}
{#<li ><a href="{% url 'base:login_view' %}">login</a> </li>#}
{#<li><a href="{% url 'base:registration_view' %}">Registration</a></li>#}
{#{% endif %}#}

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

base/templates/base/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}SNS Text Analysis{% endblock title %}

{% block content %}    

    <!-- Header -->
    <header>
        <div class="container" id="maincontent" tabindex="-1">
            <div class="row">
                <div class="col-lg-12">
                    <img class="img-responsive" src="" alt="">
                    <div class="intro-text">
                        <h1 class="name">Text Analysis</h1>
                        <hr class="star-light">
                        <span class="skills">Workplace for Text Analysis.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>




    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

{% endblock content %}